baseURL: https://margheritalatif.netlify.app/
languageCode: en-us
title: Portfolio Website for Margherita Latif
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     This is my Website for Data Analytics for Finance. 
    title: Hi, my name is Margherita Latif
  blog: {}
  contact: 
    address:
      - city: London
        country: United Kingdom
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: 'send:mlatif.mfa2022@london.edu'
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7770640640
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/MVLatif/my_website
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/margherita-latif-b02047175/
  image: Italy.jpg
  name: Margherita Latif
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Contact
        url: 'mailto:mlatif.mfa2022@london.edu'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
    menu: Menu
    subtitle: Latif 
    title: Margherita 
  tiles:
    enable: yes
    showcase:
      - image: baia-sardinia-costa-smeralda.jpg
        subtitle: Allow me to introduce myself 
        title: Biography
        url: blogs/biography
      - image: JP.jpg
        subtitle: By creating a geom error bar graph, I was able to visualise whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not
        title: IMDB ratings
        url: blogs/imdb
      - image: Gender.jpg
        subtitle: By plotting a histogram, scatterplot and boxplot, I was able to visualise the data regarding gender, pay and experience.
        title: Pay Discrimination
        url: blogs/gender
      - image: Brexit.jpg
        subtitle: Analysis of Brexit Results 
        title: Brexit results
        url: blogs/brexit
      - image: Boris.jpg
        subtitle: Analysis of bike sharing in London 
        title: Transport for London Bike Sharing
        url: blogs/tfl
  two:
    buttonText: Get Started
    enable: no
    subtitle: Welcome to my website where I have outlined a few things I enjoy to do in my spare time and to give a bit of insight into my life and background. 
    title: Introduction 
    url: blogs
