baseURL: https://margheritalatif.netlify.app
languageCode: en-us
title: Portfolio Website or Margherita Latif
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     This is my Website for Data Analytics for Finance. 
    title: Hi, my name is Margherita Latif
  blog: {}
  contact: 
    address:
      - city: London
        country: United Kingdom
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mlatif.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7770640640
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Margherita Latif
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: baia-sardinia-costa-smeralda.jpg
        subtitle: The place where I spent most of my time as a kid with my Italian family
        title: Sardegna
        url: blogs/Sardegna
      - image: darjeeling-chasing-train.jpg
        subtitle: I am a movie fanatic; one of my favourite directors is Wes Anderson
        title: Movies
        url: blogs/Movies
      - image: bn_educated.jpg
        subtitle: I enjoy reading non-fiction books for example, Educated by Tara Westover
        title: Non-Fiction Books 
        url: blogs/Non-Fiction Books
      - image: kazmal007_malevich_female_torso_large.jpg
        subtitle: I studied Modern Languages, with a major in Russian and Italian at the University of Bristol
        title: Undegraduate degree
        url: blogs/Undergraduate degree
      - image: cooking.jpg
        subtitle: I find it relaxing to cook and I have inspiration from my italian and pakistani heritage 
        title: Cooking
        url: blogs/Cooking
      - image: tennis.jpg
        subtitle: I have played tennis since I was a kid and have participated in teams at school and university
        title: Tennis 
        url: blogs/Tennis
  two:
    buttonText: Get Started
    enable: yes
    subtitle: Welcome to my website where I have outlined a few things I enjoy to do in my spare time and to give a bit of insight into my life and background. 
    title: Introduction 
    url: blogs
