---
categories:
- ""
- ""
date: "2017-10-31T21:28:43-05:00"
description: ""
draft: false
image: Gender.jpg
keywords: ""
slug: gender
title: Pay Discrimination
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>By plotting a histogram, scatterplot and boxplot, I was able to visualise the data regarding gender, pay and experience. The objective of this task was to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<p>Based on the evidence below and from looking at the p values which lay outside the 95% confidence interval, we rejected the NULL hypothesis and kept the alternative hypothesis that being the true difference in means between group female and group male is not equal to 0. There is a significant difference between experience of the male and female executives with the former being 3 times larger. This means that on average men have a stonger affiliation with a positive experience and a higher salary.</p>
<p>We conducted a more thorough analysis of the relationship between salary and experience to see whether there is any gender-based salary discrimination in the company.</p>
<p>From the scatterplot and correlation matrix, we can include that female tend to have high salary with less working experience, while male need to accumulate much higher salary to gain a little bit higher salary. Because from the figure, both the average salary and average experience of female are both smaller than the men’s; and the gap between the average experience year that the men and women accumulated, is much smaller than the gap between the average salary that female and male earned.</p>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635~
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma~
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3~</code></pre>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Can you conclude that there is a significant difference between the salaries of the male and female executives?</p>
<p>Note that you can perform different types of analyses, and check whether they all lead to the same conclusion</p>
<p>. Confidence intervals
. Hypothesis testing
. Correlation analysis
. Regression</p>
<p>Calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, you show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% condifence interval</p>
<pre class="r"><code># Summary Statistics of salary by gender
Gender_Data &lt;- mosaic::favstats (salary ~ gender, data=omega)

Gender_Data %&gt;%
  mutate(se=sd/sqrt(n)) %&gt;%
  mutate(me=2*se) %&gt;%
  mutate(ci=qnorm(0.95)*sd/se) %&gt;%
  mutate(lower_bound=mean-1.96*ci) %&gt;%
  mutate(upper_bound=mean+1.96*ci)</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing   se   me   ci
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0 1484 2968 8.39
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0 1523 3047 8.06
##   lower_bound upper_bound
## 1       64526       64559
## 2       73223       73255</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 
# the t-critical value, the standard error, the margin of error, 
# and the low/high endpoints of a 95% condifence interval</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
<p>The females have a higher SD meaning that there is more variation amongst their salaries. Since men have a higher SE of mean, that corresponds to men having a wider distribution. A higher margin of error for the men indicates that men’s sample would vary more from the real population value than women. The CI indicates how we are 95% confident that the population parameter is between 64526 and 64559 for women and 73223 and 73255 for men.</p>
<p>You can also run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. You should tun your hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package.</p>
<pre class="r"><code># hypothesis testing using t.test() 
t.test(salary ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<pre class="r"><code># hypothesis testing using infer package
ratings_in_null_world &lt;- omega %&gt;% 
  specify(salary ~ gender) %&gt;%
  hypothesize(null=&quot;independence&quot;) %&gt;%
  generate(reps = 1000, type=&quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;male&quot;, &quot;female&quot;))

ratings_in_null_world %&gt;% visualize()</code></pre>
<p><img src="/blogs/gender_files/figure-html/hypothesis_testing-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code># hypothesis testing using infer package</code></pre>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<pre class="r"><code># Summary Statistics of salary by gender
Experience_Gender &lt;- favstats (experience ~ gender, data=omega) 
Experience_Gender %&gt;%
  mutate(se=sd/sqrt(n)) %&gt;%
  mutate(me=2*se) %&gt;%
  mutate(ci=qnorm(0.95)*sd/se) %&gt;%
  mutate(lower_bound=mean-1.96*ci) %&gt;%
  mutate(upper_bound=mean+1.96*ci)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing   se   me   ci
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0 1.67 3.34 8.39
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0 2.23 4.46 8.06
##   lower_bound upper_bound
## 1       -9.05        23.8
## 2        5.33        36.9</code></pre>
<pre class="r"><code># hypothesis testing using t.test() 
t.test(experience ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<pre class="r"><code># hypothesis testing using infer package
ratings_in_null_world2 &lt;- omega %&gt;% 
  specify(experience ~ gender) %&gt;%
  hypothesize(null=&quot;independence&quot;) %&gt;%
  generate(reps = 1000, type=&quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;male&quot;, &quot;female&quot;)) 
ratings_in_null_world2 %&gt;% visualize()</code></pre>
<p><img src="/blogs/gender_files/figure-html/experience_stats-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<pre class="r"><code>ggplot(data=omega, aes(x=experience, y=salary))+
  geom_point()+
   geom_smooth(color=&quot;red&quot;, method = &quot;lm&quot;)+
  theme_bw() +
  labs (
    title = &quot;Relationship between salary and experience&quot;,
    x=&quot;experience&quot;,
    y=&quot;salary&quot;
  )</code></pre>
<p><img src="/blogs/gender_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/blogs/gender_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
